version: '3.3'
services:
  daily:
    build: 
      context: .
      dockerfile: ./Dockerfile
    container_name: restore_database
    environment:
      - MYSQL_DATABASE=xxxxxxxxxxxxx
      - MYSQL_HOST=xxxxxxxxxxxxx
      - MYSQL_PORT=xxxxxxxxxxxxx
      - MYSQL_USER=xxxxxxxxxxxxx
      - MYSQL_PASSWORD=xxxxxxxxxxxxx
      - S3_ACCESS_KEY_ID=xxxxxxxxxxxxx
      - S3_SECRET_ACCESS_KEY=xxxxxxxxxxxxx
      - S3_BUCKET=xxxxxxxxxxxxx
      - S3_REGION=xxxxxxxxxxxxx
      - S3_PATH=xxxxxxxxxxxxx
      - SQL_FILE=xxxxx.sql     
